### ISSUE TITLE
Build is failing on CGAL 5.3 or higher is required for SFCGAL master

### ISSUE THREAD

**Issue by robe2** [postgis/postgis-build-env#20]
It looks like SFCGAL master needs CGAL 5.3

Last build run failed with this error:

```
-- Setting build type to 'Release' as none was specified.
[91mCMake Error at CMakeLists.txt:54 (find_package):
  Could not find a configuration file for package "CGAL" that is compatible
  with requested version "5.3".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALConfig.cmake, version: 5.2



[0m-- Configuring incomplete, errors occurred!
See also "/src/SFCGAL/cmake-build/CMakeFiles/CMakeOutput.log".
The command '/bin/sh -c git clone --depth 1 --branch ${SFCGAL_BRANCH} https://gitlab.com/Oslandia/SFCGAL.git &&      cd SFCGAL &&      mkdir cmake-build &&      cd cmake-build &&      cmake .. &&      make -j${BUILD_THREADS} &&      make install &&      cd /src && rm -rf SFCGAL' returned a non-zero code: 1
Env Batch selected: weekly [{'name': 'latest', 'PG': 'master', 'GEOS': 'main', 'GDAL': 'master', 'PROJ': 'master', 'PG_CC': 'gcc'}, {'name': 'stable_pg14', 'PG': 'REL_14_STABLE', 'GEOS': 'main', 'GDAL': 'release/3.1', 'PROJ': '7.1', 'PG_CC': 'clang'}, {'name': 'stable_pg14', 'PG': 'REL_14_STABLE', 'GEOS': '3.9', 'GDAL': 'release/3.1', 'PROJ': '7.1', 'PG_CC': 'gcc'}]
Traceback (most recent call last):
  File "build.py", line 132, in <module>
    '.'
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '--pull', '--build-arg', 'BUILD_DATE=20210916', '--build-arg', 'POSTGRES_BRANCH=master', '--build-arg', 'GEOS_BRANCH=main', '--build-arg', 'GDAL_BRANCH=master', '--build-arg', 'PROJ_BRANCH=master', '--build-arg', 'PG_CC=gcc', '-t', 'postgis/postgis-build-env:latest', '.']' returned non-zero exit status 1.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by robe2** [comment]
As discussed in https://git.osgeo.org/gitea/postgis/postgis/pulls/56 confirmed CGAL >= 5.3 is required for SFCGAL 1.4.0 and above.  I'm going to revise to just download CGAL 5.3 as suggested by SFCGAL group

https://gitlab.com/Oslandia/SFCGAL/-/blob/master/ci/debian/before_install.sh#L11-13

.CGAL 5.3 is header-only library anyway so not like any binaries involved so doesn't add much overhead.
