### ISSUE TITLE
Build is failing on GDAL compile - can't cd to gdal/gdal

### ISSUE THREAD

**Issue by robe2** [postgis/postgis-build-env#22]
https://debbie.postgis.net/view/PostGIS/job/PostGIS-build-env/46/label=docker/consoleFull

```
[0m[91m/bin/sh: 1: cd: can't cd to gdal/gdal
[0mThe command '/bin/sh -c git clone --depth 1 --branch ${GDAL_BRANCH} https://github.com/OSGeo/gdal &&     cd gdal/gdal &&     ./autogen.sh && ./configure && make -j${BUILD_THREADS} && make install &&     cd /src && rm -rf gdal' returned a non-zero code: 2
Env Batch selected: weekly [{'name': 'latest', 'PG': 'master', 'GEOS': 'main', 'GDAL': 'master', 'PROJ': 'master', 'PG_CC': 'gcc'}, {'name': 'stable_pg14', 'PG': 'REL_14_STABLE', 'GEOS': 'main', 'GDAL': 'release/3.1', 'PROJ': '7.1', 'PG_CC': 'clang'}, {'name': 'stable_pg14', 'PG': 'REL_14_STABLE', 'GEOS': '3.9', 'GDAL': 'release/3.1', 'PROJ': '7.1', 'PG_CC': 'gcc'}]
Traceback (most recent call last):
  File "build.py", line 132, in <module>
    '.'
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '--pull', '--build-arg', 'BUILD_DATE=20211105', '--build-arg', 'POSTGRES_BRANCH=master', '--build-arg', 'GEOS_BRANCH=main', '--build-arg', 'GDAL_BRANCH=master', '--build-arg', 'PROJ_BRANCH=master', '--build-arg', 'PG_CC=gcc', '-t', 'postgis/postgis-build-env:latest', '.']' returned non-zero exit status 2.
Build step 'Execute shell' marked build as failure
```

Has been doing this for 2 weeks.

**Comment by robe2** [comment]
It looks like gdal got rid of their gdal folder in master.  Older ones had code in gdal/gdal.
Master has it directly in root.

**Comment by ImreSamu** [comment]
> It looks like gdal got rid of their gdal folder in master. Older ones had code in gdal/gdal.

my solution:    check "gdal" subdir existence:
https://github.com/postgis/docker-postgis/blob/3e5eda6bcf31155ecc205e6f5f17ab6bd2efbf6c/Dockerfile.master.template#L123-L134

**Comment by robe2** [comment]
@ImreSamu thanks for the input.  I'll test this out and make the change to ours.
