### ISSUE TITLE
Build has been failing for past 15 days -debian stable issue

### ISSUE THREAD

**Issue by robe2** [postgis/postgis-build-env#25]
```
Get:5 http://deb.debian.org/debian-security stable-security/main amd64 Packages [134 kB]
Reading package lists...
[91mE: Release file for http://deb.debian.org/debian/dists/stable-updates/InRelease is not valid yet (invalid for another 19min 23s). Updates for this repository will not be applied.
[0mThe command '/bin/sh -c apt-get update &&   apt-get install -y --no-install-recommends   autoconf   automake   bison   build-essential   ca-certificates   clang   cmake   curl   docbook-xml   docbook5-xml   eatmydata   flex   gdb   git   libboost-serialization-dev   libboost-test-dev   libboost-thread-dev   libcunit1-dev   libcurl4-gnutls-dev   libgmp-dev   libjson-c-dev   libmpfr-dev   libpcre3-dev   libprotobuf-c-dev   libreadline-dev   libsqlite3-dev   libtiff-dev   libtool   libxml2-dev   libxml2-utils   pkg-config   protobuf-c-compiler   sudo   sqlite3   valgrind   wget   xsltproc   zlib1g-dev &&   apt-get clean &&   rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
Env Batch selected: weekly [{'name': 'latest', 'PG': 'master', 'GEOS': 'main', 'GDAL': 'master', 'PROJ': 'master', 'PG_CC': 'gcc'}, {'name': 'stable_pg16', 'PG': 'REL_16_STABLE', 'GEOS': '3.12', 'GDAL': 'release/3.8', 'PROJ': '9.2.1', 'PG_CC': 'gcc'}]
Traceback (most recent call last):
  File "build.py", line 172, in <module>
    '.'
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '--pull', '--build-arg', 'BUILD_DATE=20240126', '--build-arg', 'POSTGRES_BRANCH=master', '--build-arg', 'GEOS_BRANCH=main', '--build-arg', 'GDAL_BRANCH=master', '--build-arg', 'PROJ_BRANCH=master', '--build-arg', 'PG_CC=gcc', '-t', 'postgis/postgis-build-env:latest', '.']' returned non-zero exit status 100.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

I haven't investigated the cause of this error, but might need switching the docker debian base image I presume to a newer one.

**Comment by robe2** [comment]
Seems to have resolved itself.
